/**:
  ros__parameters:
    filter_limit_min: 0
    z_max : 0.3
    z_min : -0.02
    x_max : 1.5
    x_min : -1.5
    y_max : 0.0
    y_min : -5.0
    # filter_limit_max: 1
    # filter_field_name: "z"
    keep_organized: false
    filter_limit_negative: false
